Campus.create(name: 'Abington')
@Al = Campus.create(name: 'Altoona')
Campus.create(name: 'Beaver')
Campus.create(name: 'Behrend')
Campus.create(name: 'Berks')
@BW = Campus.create(name: 'Brandywine')
Campus.create(name: 'DuBois')
Campus.create(name: 'Fayette')
Campus.create(name: 'Greater Allegheny')
Campus.create(name: 'Harrisburg, The Capital College')
Campus.create(name: 'Hazleton')
Campus.create(name: 'Lehigh Valley')
Campus.create(name: 'Mont Alto')
Campus.create(name: 'New Kensington')
Campus.create(name: 'Schuylkill')
Campus.create(name: 'Shenango')
@UP = Campus.create(name:'University Park')
Campus.create(name: 'Wilkes-Barre')
Campus.create(name: 'Worthington Scranton')
Campus.create(name: 'York')