@SHaynes = Instructor.create(first_name:'Steven', last_name:'Haynes')
@AGarbrick = Instructor.create(first_name:'Amy', last_name:'Garbrick')
@JKropczynski = Instructor.create(first_name:'Jessica', last_name:'Kropczynski')
@MDuffey = Instructor.create(first_name:'Michele', last_name:'Duffey')
@SChallis = Instructor.create(first_name:'Susan', last_name:'Challis')
@SFrance = Instructor.create(first_name:'Sarah', last_name:'France')
@AMurphy = Instructor.create(first_name:'Allison', last_name:'Murphy')
@EBrady = Instructor.create(first_name:'Elizabeth', last_name:'Brady')
@KMarin = Instructor.create(first_name:'Kellie', last_name:'Marin')
@DManthey = Instructor.create(first_name:'Dominic', last_name:'Manthey')
@DBrinker = Instructor.create(first_name:'David', last_name:'Brinker')
@JNussbaum = Instructor.create(first_name:'Jon', last_name:'Nussbaum')
@EWomack = Instructor.create(first_name:'Elizabeth', last_name:'Womack')
@TFitts = Instructor.create(first_name:'Timothy', last_name:'Fitts')
@AVega = Instructor.create(first_name:'Anthony', last_name:'Vega')
@AMuir = Instructor.create(first_name:'Allen', last_name:'Muir')
@WCampbell = Instructor.create(first_name:'William', last_name:'Campbell')
@MKananen = Instructor.create(first_name:'Mary', last_name:'Kananen')

#Instructor.create(first_name:'', last_name:'')
