# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5f062c714dd132d4e1f17934420bdfda6db9996f88955a7dbb1d9c55ddd374b36af4db1b125ceb61a17672e9d684282dcfb11c4780f4959fe0386c009a40a2f3

test:
  secret_key_base: 8517c0be071c6eb381299c3ab1c81d1b41d11b4a3d1d67509528c404c04fde0d7c252b631d7106bc0954200f780daef1c8f47f3b20b2936fded9e821d3f7c00f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
